apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-program
  namespace: java-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-program
  template:
    metadata:
      labels:
        app: java-program
    spec:
      containers:
        - name: java-program
          image: manish28/java_program_k8:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080